[iperf]
language = "c"
compile_commands_path = "database/iperf/latest/build_asan/compile_commands.json"
header_paths = ["database/iperf/latest/code/src/cjson.h"]
document_paths = ["database/iperf/latest/code/src/cjson.h"]
document_has_api_usage = false
output_path = "database/iperf/latest/out"
driver_build_args = [
    "database/iperf/latest/build_asan/libcjson.a",
    "-Idatabase/iperf/latest/code/src",
    "-lm",
]
consumer_case_paths = []
consumer_build_args = []
source_paths = []
exclude_paths = []
driver_headers = []
api_hints_path = ""
