// Manual fuzz driver targeting hwloc_encode_to_base64.
// Generated by hand because PromeFuzz's all-cover mode skipped this private
// API on its own; placing the driver in the existing fuzz_driver directory
// lets match_and_fuzz pick it up against the gold target_function.
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>

extern int hwloc_encode_to_base64(const char *src, size_t srclength,
                                  char *target, size_t targsize);

int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    if (Size == 0 || Size > 4096) return 0;
    // base64 expansion is ceil(srclen/3)*4 + 1; allocate generously.
    size_t targsize = ((Size + 2) / 3) * 4 + 16;
    char *target = (char *)malloc(targsize);
    if (!target) return 0;
    hwloc_encode_to_base64((const char *)Data, Size, target, targsize);
    free(target);
    return 0;
}
